version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: patrimonio_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sgpi
    ports:
      - "9306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
